import 'dart:typed_data';

import 'package:cross_file/cross_file.dart';
import 'package:nhost_dart/nhost_dart.dart';

/// Flutter-specific extensions on [NhostStorageClient].
///
/// Adds [XFile] upload support so files from `image_picker`, `file_picker`,
/// or any other cross-platform file API can be uploaded with a single call.
extension NhostStorageFlutterExtension on NhostStorageClient {
  /// Uploads an [XFile] (from `image_picker`, `file_picker`, etc.) to storage.
  ///
  /// [bucketId] — optional target bucket (uses the project default if omitted).
  /// [fileId] — optional custom ID; a UUID is generated by the server otherwise.
  /// [metadata] — optional custom metadata to attach to the file.
  /// [onUploadProgress] — callback fired during upload with bytes sent and total.
  ///
  /// Returns [FileMetadata] for the uploaded file.
  ///
  /// Example:
  /// ```dart
  /// final picker = ImagePicker();
  /// final xFile = await picker.pickImage(source: ImageSource.gallery);
  /// if (xFile != null) {
  ///   final meta = await Nhost.instance.storage.uploadXFile(
  ///     xFile,
  ///     onUploadProgress: (sent, total) => print('$sent / $total'),
  ///   );
  ///   final url = Nhost.instance.storage.publicUrl(meta.id);
  /// }
  /// ```
  Future<FileMetadata> uploadXFile(
    XFile file, {
    String? bucketId,
    String? fileId,
    Map<String, dynamic>? metadata,
    UploadProgressCallback? onUploadProgress,
  }) async {
    final bytes = Uint8List.fromList(await file.readAsBytes());
    final mimeType = file.mimeType ?? _guessMimeType(file.name);

    final results = await uploadFiles(
      files: [
        FileData(bytes, filename: file.name, contentType: mimeType),
      ],
      bucketId: bucketId,
      metadataList: (fileId != null || metadata != null)
          ? [UploadFileMetadata(id: fileId, name: file.name, metadata: metadata)]
          : null,
      onUploadProgress: onUploadProgress,
    );

    return results.first;
  }

  /// Uploads raw [Uint8List] bytes — useful when working directly with Flutter
  /// image/canvas APIs that produce bytes rather than files.
  ///
  /// [fileName] must include the extension so the MIME type can be inferred.
  ///
  /// Named `uploadRawBytes` to avoid shadowing the deprecated
  /// `uploadBytes` instance method on [NhostStorageClient].
  Future<FileMetadata> uploadRawBytes(
    Uint8List bytes, {
    required String fileName,
    String? mimeType,
    String? bucketId,
    String? fileId,
    Map<String, dynamic>? metadata,
    UploadProgressCallback? onUploadProgress,
  }) async {
    final resolvedMime = mimeType ?? _guessMimeType(fileName);

    final results = await uploadFiles(
      files: [
        FileData(bytes, filename: fileName, contentType: resolvedMime),
      ],
      bucketId: bucketId,
      metadataList: (fileId != null || metadata != null)
          ? [UploadFileMetadata(id: fileId, name: fileName, metadata: metadata)]
          : null,
      onUploadProgress: onUploadProgress,
    );

    return results.first;
  }
}

String _guessMimeType(String fileName) {
  final ext = fileName.split('.').last.toLowerCase();
  return const {
    'jpg': 'image/jpeg',
    'jpeg': 'image/jpeg',
    'png': 'image/png',
    'gif': 'image/gif',
    'webp': 'image/webp',
    'svg': 'image/svg+xml',
    'mp4': 'video/mp4',
    'mov': 'video/quicktime',
    'pdf': 'application/pdf',
    'json': 'application/json',
    'txt': 'text/plain',
    'csv': 'text/csv',
  }[ext] ??
      'application/octet-stream';
}
